server:
  port: 80
spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 172.23.46.70
    password:
  session:
    timeout: 1800 # session 超时时间，单位秒
mybatis-plus:
  type-aliases-package: cn.icexmoon.bootdemo.entity
shiro:
  loginUrl: /jsp/user/login.jsp
